on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      desktop--release_created: ${{ steps.release.outputs['apps/desktop--release_created'] }}
      desktop--release_id: ${{ steps.release.outputs['apps/desktop--id'] }}
      desktop--tag_name: ${{ steps.release.outputs['apps/desktop--tag_name'] }}
    steps:
      - uses: Fanzzzd/release-please-action@release-with-force-tag
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  desktop-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.desktop--release_created == 'true' }}
    uses: ./.github/workflows/release-desktop.yml
    with:
      tag_name: ${{ needs.release-please.outputs.desktop--tag_name }}
    secrets: inherit
