on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      desktop--release_created: ${{ steps.release.outputs['apps/desktop--release_created'] }}
      desktop--release_id: ${{ steps.release.outputs['apps/desktop--id'] }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install release-please fork
        run: npm install Fanzzzd/release-please#feat/draft-release-force-tag @actions/core
      - name: Run release-please
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/run-release-please.js

  desktop-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.desktop--release_created == 'true' }}
    uses: ./.github/workflows/release-desktop.yml
    with:
      release_id: ${{ needs.release-please.outputs.desktop--release_id }}
    secrets: inherit
